version: '3.8'

services:
  redis-service:
    image: redis:7.0.15-alpine

  backend: 
    image: jeysonflores/backend
    build: ./material-applications/example-backend
    environment:
      - REDIS_HOST=redis-service
      - REQUEST_ORIGIN=*
    ports:
      - 8080:8080
  
  frontend:
    image: jeysonflores/frontend
    build: ./material-applications/example-frontend
    ports:
      - 5050:5050